---
==================================================
#Copy stdout to a file
- tasks:
    - raw: "{{ show arp }}"
      register: show
      #Puts output of the show command into the "show variable"
    - local_action: > #Represents multiline task. Local action denotes it being done on the ansible host
        copy content={{ show.stdout }}
             dest={{ inventory_hostname }}.arp.txt
      run_once: true #Used to prevent multiple runs if running on localhost but the task falls under multiple host

==================================================
#Error handling
- hosts: ios
  tasks:
  - ios_command:
      commands: show version
      provider: "{{ cli }}"
    register: result
  - fail: msg="Wrong Cisco IOS version"
    when: "not ('Version {{ version }}' in result.stdout[0])"

==================================================
#Preventing runs when certain variables are not defined
- name: Generate device configs
  connection: local
  tasks:
  - assert:
      that:
        - syslog_host is defined
        - snmp_host is defined
      msg: One of the NMS servers is not defined

==================================================
#Rescue block
- hosts: ios
  tasks:
  - block:
      - list of actions
    rescue:
      - actions to execute on failure
    always:
      - actions to execute at the end no matter what.

==================================================
#File management (Relevant to ansible host on localhost)
- hosts: localhost
  connection: local
  tasks:
  - file: path=version_report.txt state=absent
  - file: path=version_report.txt state=touch
  #Additional file options - (file, directory, link, hardlink)

==================================================
#Adding lines to a text file
- lineinfile:
    dest: version_report.txt
    regexp: "{{ inventory_hostname }}"
    line: "{{ inventory_hostname }}" has wrong IOS version"
  when: "not ('Version {{ version }}' in result.stdout[0])"

==================================================
#Adding blocks to text files
- blockinfile:
    dest: results.txt
    marker: "### { mark } {{ inventory_hostname }}"
    block: result.stdout[0]

#Marker - Text identifying the begin/end of a block
#Block - Block content
#Backup - Create backup copy before modification
#Create - Create a file if it doesn't exist

==================================================
#Assembling multiple files into an output file
- assemble:
    src: directory_path
    regex: file_matching_pattern (Optional)
    dest: file_path
#remote_src: true - Used if source file is on the hose

==================================================
#Summary Report: Configuration changes
- name: Document changes
  copy:
    content: |
      **************************************************
      {{ component }} changes on {{ inventory_hostname }}
      **************************************************
      {% for line in changes.commands %}
      {{ line }}
      {% endfor %}
    dest: "{{ configures }}/changes/
           {{ inventory_hostname }}.{{ component }}.changes"
  delegate_to: localhost

==================================================
#Simple loop for a list
- hosts: ios
  tasks:
  - name: "Ping targets from IOS devices"
    ios_command: commands="ping {{ item }}"
    register: results
    with_items: "{{ ping_target }}"

==================================================
#Simple loop for a dict
- hosts: ios
  tasks:
  - name: "Ping targets from IOS devices"
    ios_command: commands="show standby neigh {{ item.key }}"
    register: results
    with_dict: "{{ interfaces }}"

==================================================
#Loop until a condition is met
- hosts: ios
  tasks:
  - name: "Check interface status"
    ios_command: commands="show interface dialer 1"
    register: ifstate
    until: ifstate.stdout[0].find("protocol is up" ) > 0
    retries: 5
    delay: 10

==================================================
#Select subset of elements from a list
name: |
  vlans|selectattr('id','equalto',target_vlan)|
  map)attribute='name')|first

vlans:
  - { id: "100", name: "mgmt", subnet: "172.16.21.0/24"}
  - { id: "101", name: "web", subnet: "192.168.22.0/24"}

==================================================
#Extract data from text printout
- ios_command:
    commands: "show ip interface brief | exclude Interface"
  register: printout
- set_fact:
    intf: |
      {{ printout.stdout_lines[0] |
         map('regex_findall','^([A-Za-z]+[0-9./]+)') |
         map('join') | list }}
#regex_findall performs regex match and returns a list of matches
#join within a map merges inner lists into strings
#map is a generator

==================================================
#Overwriting the changed flag (In case you don't want)
#to represent something as "changed" after completion
- hosts: all
  tasks:
  - file: path={{ build_dir }} state=directory
    run_once: yes
    changed_when: false

==================================================
#Check mode for a dry run
- ios_config:
    src: "config file.config"
  register: changes
- copy:
    content: |
      {% if ansible_check_mode %}
      === Running in check mode ===
      {% endif %}
      {% for line in changes.commands %}
      {{ line }}
      {% endfor %}
    dest: "destination file.config"
  check_mode: yes

==================================================
#Prepopulate SSH known_hosts file
https://github.com/ipspace/NetOpsWorkshop/tree/master/tools/ssh-keys

==================================================
#Authorize connection (Enable mode)
- tasks:
  - ios_command:
      commands: show arp
      authorize: yes