---
- hosts: SW4
  gather_facts: no
  connection: local

  tasks:
    - ios_config:
        lines:
          - hostname SWITCH4
        provider: "{{ cli }}"
      register: result
    - debug: var=result
